<?php
/**
 * @var \MODX\Revolution\modX $modx
 * @var array $namespace
 */

// Include autoloader generated by your composer
require_once $namespace['path'] . 'vendor/autoload.php';

// Register base class in the service container
$modx->services->add('lesscss', function($c) use ($modx) {
    return new \LessCSS\v3\LessCSS($modx);
});